services:
  eas-builder:
    container_name: eas-builder
    image: eas-builder:2.0
    build:
      context: .
      dockerfile: Dockerfile
    env_file: eas.env
    deploy:
      resources:
        limits:
          cpus: "8"
          memory: "16G"
