FROM node:18.18.0-slim as builder

# Atualizando e instalando pacotes necessários
RUN apt update && apt upgrade -y && apt install curl unzip zip curl gh -y;

# Envs
ENV JAVA_HOME="/usr/lib/jvm/java-17-openjdk-amd64"
ENV ANDROID_HOME="$HOME/android"
ENV ANDROID_SDK_ROOT="$ANDROID_HOME"
ENV ANDROID_NDK_HOME="$HOME/android/ndk/android-ndk-r26d"
ENV PATH="$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$PATH"
ENV EAS_LOCAL_BUILD_SKIP_CLEANUP=0
ENV EAS_LOCAL_BUILD_ARTIFACTS_DIR="/build/eas-build-artifacts"
ENV EAS_LOCAL_BUILD_WORKINGDIR="/build/eas-local-build-workingdir"
ENV EAS_BUILD_WORKER_DIR="/build/eas-build-worker-dir"

# Instalando Java 17
RUN apt install openjdk-17-jdk -y;
RUN java --version;

# Instalando Android Command-line Tools
RUN cd ~;
COPY ./tools/commandlinetools-linux-11076708_latest.zip /tmp/cmd-tools.zip
RUN mkdir -p android/cmdline-tools;
RUN unzip -q -d android/cmdline-tools /tmp/cmd-tools.zip;
RUN mv android/cmdline-tools/cmdline-tools android/cmdline-tools/latest;
RUN rm /tmp/cmd-tools.zip;
RUN yes | sdkmanager --licenses;
RUN sdkmanager --update;

# Configurando o Android NDK (Native Development Kit)
RUN cd ~;
COPY ./tools/android-ndk-r26d-linux.zip /tmp/ndk.zip
RUN mkdir -p android/ndk;
RUN unzip -q -d android/ndk /tmp/ndk.zip;
RUN rm /tmp/ndk.zip;

# Instalando EAS CLI (Expo Application Services Command Line Interface)
RUN npm install -g \
    npm@9.8.1 \
    yarn@1.22.19 \
    pnpm@8.9.2 \
    eas-cli@latest \
    sharp-cli \
    node-gyp@10.0.1 \
    bun@1.0.14 --force;

# Script principal
COPY dist/main.js /usr/local/bin/main.js
RUN chmod +x /usr/local/bin/main.js

# Criar diretórios
RUN mkdir -p /project
RUN mkdir -p /build/eas-build-artifacts
RUN mkdir -p /build/eas-local-build-workingdir
RUN mkdir -p /build/eas-build-worker-dir

# Definir o diretório de trabalho
WORKDIR /project