FROM node:18.18.0-slim AS builder

# Atualizando e instalando pacotes necessários
RUN apt update && \
    apt upgrade -y && \
    apt install -y curl unzip zip git && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

# Envs
ENV JAVA_HOME="/opt/java/openlogic-openjdk-17.0.14+7-linux-x64"
ENV PATH="$JAVA_HOME/bin:$PATH"

ENV ANDROID_HOME="/root/android"
ENV ANDROID_SDK_ROOT="/root/android"
ENV ANDROID_NDK_HOME="$ANDROID_HOME/ndk/android-ndk-r26d"
ENV PATH="$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$PATH"

ENV EAS_LOCAL_BUILD_SKIP_CLEANUP=0
ENV EAS_LOCAL_BUILD_ARTIFACTS_DIR="/build/eas-build-artifacts"
ENV EAS_LOCAL_BUILD_WORKINGDIR="/build/eas-local-build-workingdir"
ENV EAS_BUILD_WORKER_DIR="/build/eas-build-worker-dir"

# Instalando Java 17
# https://builds.openlogic.com/downloadJDK/openlogic-openjdk/17.0.14+7/openlogic-openjdk-17.0.14+7-linux-x64.tar.gz
COPY ./tools/openlogic-openjdk-17.0.14+7-linux-x64.tar.gz /tmp/openjdk.tar.gz
RUN mkdir -p /opt/java && \
    tar -xzf /tmp/openjdk.tar.gz -C /opt/java && \
    rm /tmp/openjdk.tar.gz;

# Instalando Android Command-line Tools
# https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip?hl=pt-br
COPY ./tools/commandlinetools-linux-11076708_latest.zip /tmp/cmd-tools.zip
COPY ./tools/commandlinetools-linux-11076708_latest.zip /tmp/cmd-tools.zip
RUN mkdir -p $ANDROID_HOME/cmdline-tools && \
    unzip -q /tmp/cmd-tools.zip -d $ANDROID_HOME/cmdline-tools && \
    mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest && \
    rm /tmp/cmd-tools.zip && \
    yes | sdkmanager --licenses && \
    sdkmanager --update;

# Configurando o Android NDK (Native Development Kit)
# https://dl.google.com/android/repository/android-ndk-r26d-linux.zip
COPY ./tools/android-ndk-r26d-linux.zip /tmp/ndk.zip
RUN mkdir -p $ANDROID_HOME/ndk && \
    unzip -q /tmp/ndk.zip -d $ANDROID_HOME/ndk && \
    rm /tmp/ndk.zip;

# Instalando EAS CLI (Expo Application Services Command Line Interface)
# Instalando ferramentas globais
RUN npm install -g \
    npm@9.8.1 \
    yarn@1.22.19 \
    pnpm@8.9.2 \
    eas-cli@latest \
    sharp-cli \
    node-gyp@10.0.1 \
    bun@1.0.14 --force

# Script principal
COPY dist/main.js /usr/local/bin/main.js
RUN chmod +x /usr/local/bin/main.js

# Criar diretórios
RUN mkdir -p /project \
    /build/eas-build-artifacts \
    /build/eas-local-build-workingdir \
    /build/eas-build-worker-dir

# Diretório de trabalho
WORKDIR /project